[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
# Updated to Leptos 0.8
leptos = { version = "0.8", features = ["csr"] }
leptos_meta = { version = "0.8", features = ["csr"] }
leptos_router = { version = "0.8", features = ["csr"] }

# WASM and browser dependencies - Updated
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gloo-net = { version = "0.6", features = ["http"] }
gloo-timers = { version = "0.3", features = ["futures"] }

# Utilities - Updated
chrono = { version = "0.4", features = ["serde", "wasmbind"] }
uuid = { version = "1.10", features = ["v4", "serde", "js"] }
console_error_panic_hook = "0.1"
js-sys = "0.3"
tracing = "0.1"
regex = "1.10"
rust_decimal = { version = "1.36", features = ["serde"] }
validator = { version = "0.18", features = ["derive"] }

web-sys = { version = "0.3", features = [
  "console", "Window", "Document", "Element", 
  "HtmlElement", "Storage", "Location",
  "HtmlInputElement", "HtmlSelectElement"
]}