[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
dotenv = { workspace = true }

# Database-specific dependencies